name: Surabie_S_clean_v2
channels:
  - defaults
dependencies:
  - pandas
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - ipykernel
  - scikit-learn
  - optuna
  - pathlib
  - scikit-optimize
  - seaborn
  - kneed
  - rdkit
  - plotly
  - imbalanced-learn
  - xgboost
